 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quotations", type: :request do
  
  # Quotation. As you add validations to Quotation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Quotation.create! valid_attributes
      get quotations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quotation = Quotation.create! valid_attributes
      get quotation_url(quotation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quotation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      quotation = Quotation.create! valid_attributes
      get edit_quotation_url(quotation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Quotation" do
        expect {
          post quotations_url, params: { quotation: valid_attributes }
        }.to change(Quotation, :count).by(1)
      end

      it "redirects to the created quotation" do
        post quotations_url, params: { quotation: valid_attributes }
        expect(response).to redirect_to(quotation_url(Quotation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Quotation" do
        expect {
          post quotations_url, params: { quotation: invalid_attributes }
        }.to change(Quotation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post quotations_url, params: { quotation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quotation" do
        quotation = Quotation.create! valid_attributes
        patch quotation_url(quotation), params: { quotation: new_attributes }
        quotation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quotation" do
        quotation = Quotation.create! valid_attributes
        patch quotation_url(quotation), params: { quotation: new_attributes }
        quotation.reload
        expect(response).to redirect_to(quotation_url(quotation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        quotation = Quotation.create! valid_attributes
        patch quotation_url(quotation), params: { quotation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quotation" do
      quotation = Quotation.create! valid_attributes
      expect {
        delete quotation_url(quotation)
      }.to change(Quotation, :count).by(-1)
    end

    it "redirects to the quotations list" do
      quotation = Quotation.create! valid_attributes
      delete quotation_url(quotation)
      expect(response).to redirect_to(quotations_url)
    end
  end
end
